### PR TITLE
remove windows phone templates

### PR DESCRIPTION
**Pull request by emilioicai**

### CODE REVIEW

**Comment by secondsun** [comment]
+1

**Comment by pmdarrow** [comment]
@emilioicai there's a few references to Windows Phone in the README:

```
README.md
5:Technologies: Windows Phone
14:This project is a very simple helloworld, to show how to get started with Windows Phone and the UnifiedPush Server
```

**Comment by emilioicai** [comment]
Actually I didn't realise Windows Phone is the only valid project here. @wtrocki Maybe we should remove this repo completely?

**Comment by wtrocki** [comment]
@emilioicai How about removing it in global.json and leave note in the repo for now?

**Comment by emilioicai** [comment]
sounds good to me

**Pull request merged**
